### ISSUE TITLE
Comparative study between Kafka and RabbitMQ to define the implementation in the transaction domain

### ISSUE THREAD

**Issue by gitfelipegomes** [LerianStudio/midaz#188]
## Context

We need to define the queue system that will be implemented in the context of transactions for asynchronous processing.

## How to do it?

Raise the pros and cons of each system and open a discussion thread to define which one will be used.

**Comment by MartinezAvellan** [comment]
**Kafka**

- Scalability: Designed to handle large data volumes and high throughput, Kafka is suitable for applications needing real-time event processing at scale.

- Data Persistence: Kafka stores events for a configurable period, allowing consumers to read historical events or recover messages after failures, making it ideal for systems where event history is crucial.

- Real-Time Streaming: Kafka excels with continuous data streams, where data needs sequential, fast processing, as in real-time analytics systems.

- Latency: Works well for systems where latency can be slightly higher, with a focus on batch processing and high throughput.

**RabbitMQ**

- Traditional Messaging: Built as a queue-oriented messaging system, RabbitMQ is excellent for message exchange between microservices and scenarios requiring direct, low-latency communication.

- Routing and Forwarding: Offers flexible message routing with multiple exchange patterns (Fanout, Direct, Topic), making it easy to configure different message flows.

- Retention: Typically, RabbitMQ doesn’t store messages long-term as Kafka does; messages are processed and discarded after the consumer reads them, so it's better for systems where message retention isn't a priority.

- Latency: Usually has lower latency than Kafka, ideal for use cases needing fast, direct communication between services.


In my viewpoint for a payment transfer system using event-driven, **RabbitMQ** is likely the better choice due to its:

- Strong reliability and message delivery guarantees
- Flexible routing capabilities
- Low latency performance
- Simpler consumer development model

RabbitMQ's features align well with the requirements of financial transactions, where message reliability, ordering, and quick processing are paramount.

- https://aws.amazon.com/compare/the-difference-between-rabbitmq-and-kafka
- https://www.simplilearn.com/kafka-vs-rabbitmq-article

**Comment by gitfelipegomes** [comment]
@MartinezAvellan In my view we can proceed with RabbitMQ given the information collected above.
